apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base/app
  - ../../base/ingress

patches:
  - target:
      kind: Ingress
      name: my-app-ingress
      namespace: prod
    path: ingress-patch.yaml