apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-app-multi
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: dev
            path: overlays/dev
            namespace: dev
          - name: alpha
            path: overlays/alpha
            namespace: alpha
          - name: prod
            path: overlays/prod
            namespace: prod
  template:
    metadata:
      name: my-app-{{name}}
    spec:
      project: default
      source:
        repoURL: https://github.com/Katsu0424/play-manifest.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true